### ISSUE TITLE
Compile the new code. 

### ISSUE THREAD

**Issue by PrincessKimchi** [utarwyn/SuperJukebox#10]
Can you compile the lastest code because it has the 1.15/1.14 fixes and bug fix. Thanks

**Comment by utarwyn** [comment]
Hello @PrincessKimchi,

I agree with you, it's a good idea to release a new version of the plugin with the support of 1.14 and 1.15 versions. @TheCoolOne123, maybe you can push a new version on Spigot forums ? I can also bump the plugin version to 1.2.0 and create a Jar on the releases page on Github if you want.

Regards

**Comment by PrincessKimchi** [comment]
Thanks for the quick response. I hope to be seeing the newly updated plugin soon. Also, I think you can release this as 1.14.x,1.15.x,1.16.x-SNAPSHOT support because the block mapping of 1.14-1.16 is all the same just a tip. Thanks again for the quick response.

**Comment by utarwyn** [comment]
I have released the version **0.2.0** of the plugin on **Github**. Now you will find all releases on "Github Releases" section (find the latest version [here](https://github.com/utarwyn/SuperJukebox/releases/latest)). You can open a new issue or join our Discord server if you have a problem with the plugin.

I'm not the administrator of the plugin's page on Spigot forums so I can't release the latest version on it (I hope @TheCoolOne123 could do that for me 😄).
