### ISSUE TITLE
Support Minecraft 1.17/1.18

### ISSUE THREAD

**Issue by utarwyn** [utarwyn/SuperJukebox#23]

**Comment by CSchank** [comment]
Is there any ETA on this by any chance?

**Comment by utarwyn** [comment]
Hello! I have just released a new version of the plugin which adds this support (**v0.4.0**). 🚀 
Check more details of the release here: https://github.com/utarwyn/SuperJukebox/releases/tag/v0.4.0

You can download the plugin Jar file from the release page or from my Jenkins service:
https://ci.utarwyn.fr/job/SuperJukebox/
