### ISSUE TITLE
Sponge Port

### ISSUE THREAD

**Issue by Waterpicker** [utarwyn/SuperJukebox#3]
Hello there. I'm interested in porting your plugin to the Sponge Plugin API. I won't require any help from you directly to pull this off. Your codebase is pretty easy to follow and I have a firm understanding how to translate spigot code into sponge api pretty well. Just wondering what you thoughts and opinions on this is.

**Comment by TheCoolOne123** [comment]
Wow, this is a nice thing (**For newbies**: Sponge makes is possible to use plugins on a forge server (Where you install mods on) this guy want's to make the plugin also available on Sponge)

P.s. @utarwyn ;)

**Comment by Waterpicker** [comment]
Its more than just plugins with mods. Sponge is a full fledged plugin API with a Vanilla Version that makes it a direct competitor with Spigot. :D

**Comment by utarwyn** [comment]
Well, why not! I'm happy to see that you are interested by porting the plugin on Sponge.

Can you keep the same code base and create a plugin that supports **both Spigot and Sponge**? I am a newbie on Sponge sorry haha. If you can, this might be cool to push all changes in this repo (with PRs). 

**Anyway, thank you!**

**Comment by Waterpicker** [comment]
Yea! I just joined discord yesterday after writing the issue. We can discuss what parts of your plugin would have to be rewritten to allow this common code structure. :D
