### ISSUE TITLE
Wrong song duration

### ISSUE THREAD

**Issue by utarwyn** [utarwyn/SuperJukebox#6]
On test songs, we have a large offset between the time displayed in the tooltip and the veritable duration of the song. The displayed time seems to be 2 times less than the original.

![image](https://user-images.githubusercontent.com/9255967/50379850-0f96b580-0656-11e9-8600-1422a0b616fc.png)

We have to work on that. @TheCoolOne123, have you the same problem than me?

**Comment by TheCoolOne123** [comment]
I checked some code, and it should be somewhere here:
https://github.com/utarwyn/SuperJukebox/blob/d6326125a6b2bb7e223b7ce73181814244ee7763/src/main/java/fr/utarwyn/superjukebox/music/Music.java#L156-L161

(This is a wild guess)

**Comment by utarwyn** [comment]
Yep, I will look into that part of the code next days! 😄

**Comment by utarwyn** [comment]
Fixed with the commit 1bec4cd7a48b894082ce75680691540b2b462f22
