### ISSUE TITLE
Support new NBS format

### ISSUE THREAD

**Issue by utarwyn** [utarwyn/SuperJukebox#8]
To make Note Block Studio work better in the future, **the .nbs format has changed**.
SuperJukebox **does not support this new format for now**. So we have to work on that.

## Changes
The first 2 bytes (used to be song length) have been changed to 0 to indicate the new format.

After this, the next byte is the .nbs version. Right now that version is 1, but if the nbs format needs changes in the future, it will be different.

The byte after that is the first custom instrument index. Example: If there are 10 'normal' instruments, 10 is the first index of the custom instruments (remember, we start counting from 0).

The rest of the format is the same, with song height being the next short.

**Comment by TheCoolOne123** [comment]
Note we also need to try and make support for the old one

**Comment by HielkeMinecraft** [comment]
I see you copied the readme info. Sadly, the readme is outdated. 
We are now at version 2. Version 2 added the sound panning to the left/right.

I just updated the readme. My bad :)

**Comment by utarwyn** [comment]
I have created a new branch to work on this issue.
You can find it here: https://github.com/utarwyn/SuperJukebox/commits/feature/1.2_support-all-nbs-formats

As you told few months ago, my description of the new format is not correct.
The official changelog of the improved format is on your website: https://hielkeminecraft.github.io/OpenNoteBlockStudio/nbs
